### ISSUE TITLE
setup.py fails with NameError while creating data directories

### ISSUE THREAD

**Issue by thakkardharmik** [CruiseDevice/twweet-cli#38]
```
User:twweet-cli $ sudo python setup.py install
Password:
running install
Creating Data Directories...
Enter your Consumer Key: kub6U1JlLscNSchFseOoSwLRaancn
Traceback (most recent call last):
  File "setup.py", line 87, in <module>
    'twweet-cli = twweet_cli:main',
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 24, in run
    createCreds()
  File "setup.py", line 38, in createCreds
    ck = input('Enter your Consumer Key: ').strip()
  File "<string>", line 1, in <module>
NameError: name 'kub6U1JlLscNSchFseOoSwLRaancn' is not defined
```

**Comment by 0x006E** [comment]
Let me try it. I didn't test on a Mac. Thanks for the info

**Comment by CruiseDevice** [comment]
@thakkardharmik try doing `sudo python3 setup.py install`

**Comment by CruiseDevice** [comment]
and let me know if it works.

**Comment by CruiseDevice** [comment]
Fixed this issue. You can check by deleting old data dir if any present and then doing `sudo python3 setup.py  install`. While installing, prompt will ask for twitter api credentials. Fill it and then you are good to test the app.
