### ISSUE TITLE
setup.py failing @ os.chmod

### ISSUE THREAD

**Issue by thakkardharmik** [CruiseDevice/twweet-cli#40]
Traceback (most recent call last):
  File "setup.py", line 92, in <module>
    'twweet-cli = twweet_cli:main',
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 25, in run
    createCreds()
  File "setup.py", line 53, in createCreds
    os.chmod(home+"/.twweet-cli/data/creds.json")
TypeError: Required argument 'mode' (pos 2) not found

**Comment by thakkardharmik** [comment]
I have fixed this issue. Please provide access to commit to the master branch for 3.X.

**Comment by CruiseDevice** [comment]
@thakkardharmik create a PR to master branch directly. I will check and then merge.

**Comment by CruiseDevice** [comment]
i have fixed this. you can check if everything is working fine.
