### ISSUE TITLE
Unable to run twweet-cli

### ISSUE THREAD

**Issue by screwgoth** [CruiseDevice/twweet-cli#70]
I followed the instruction in the README file : Cloned the repo, made a python3 virtual environment, installed tweepy (Also needed to install pyyaml). Then when I ran `twweet-cli` , as expected, I was asked the Consumer Key and the Access Token credentials, which  I duly entered after creating a Twitter App.
After this, when I run `twweet-cli` or `twweet-cli --help` or `twweet-cli -h` or `twweet-cli help` I get the following error:
`
Traceback (most recent call last):
  File "/home/user/.virtualenvs/env3/bin/twweet-cli", line 11, in <module>
    load_entry_point('twweet-cli==1.0.0', 'console_scripts', 'twweet-cli')()
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/twweet_cli/main.py", line 1, in <module>
    from .Twweeter import Twweeter
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/twweet_cli/Twweeter.py", line 10, in <module>
    Configuration = ConfigurationReader()
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/twweet_cli/config/ConfigReader.py", line 17, in __init__
    cfg = yaml.load(ymlfile)
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/yaml/scanner.py", line 128, in peek_token
    self.fetch_more_tokens()
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/home/user/.virtualenvs/env3/lib/python3.5/site-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/home/user/.twweet-cli/data/config.yml", line 4, column 19
`

Unable to proceed further.

**Comment by nithinswarrier** [comment]
Please post your config.yml. Only post after replacing your twitter id's from the file.

**Comment by screwgoth** [comment]
My config.yml file is empty:
`

            #Depending on the system(Windows or Linux)
            change the backward or forward slash appropriately.
            Tweets: /TweetsStore/

            HashTag : /HashTagStore/

`

**Comment by 0x006E** [comment]
Please remove the space between "HashTag" and the ":". Now try again to start it.

**Comment by screwgoth** [comment]
Nope. That doesn't help either.

**Comment by 0x006E** [comment]
Okay then. Let me try to reproduce the issue

**Comment by 0x006E** [comment]
Hi. Can you try now again. I have fixed the issue. please clone the repo and try again. Thanks and feel free to report more

**Comment by screwgoth** [comment]
+1 
It works !!!
